language: node_js
sudo: required
dist: trusty
node_js:
  - "5.1"

services:
  - postgresql

addons:
  postgresql: "9.5"

install:
  - npm install
  - npm run deploy_dbs
  
script:
  - npm test

webhooks:
    urls:
        - https://webhooks.gitter.im/e/c6efa15aba2be0d915e0
